#!/bin/bash
#SBATCH -A mp309
#SBATCH -N 01
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J fix
#SBATCH --ntasks-per-node=32
#SBATCH -t 00:30:00

#OpenMP settings:
# export OMP_NUM_THREADS=1
# export OMP_PLACES=threads
# export OMP_PROC_BIND=spread

#run the application:
srun -n 32 ./fix-flux -nt 10 -n 1024 -m 1024 > bm-010-1024-1024-01-32-fix.out
