#!/bin/bash
#SBATCH -A mp309
#SBATCH -N 01
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J var
#SBATCH --ntasks-per-node=01
#SBATCH -t 00:30:00

#OpenMP settings:
# export OMP_NUM_THREADS=1
# export OMP_PLACES=threads
# export OMP_PROC_BIND=spread

#run the application:
srun -n 01 ./sn-var-flux -nt 10 -n 004 -m 004 > bm-010-004-004-01-01-var.out
