#!/bin/bash
#SBATCH -A mp309
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J fenicsx
#SBATCH --ntasks-per-node=2
#SBATCH -t 00:30:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
srun -n 2 python fix-fenicsx.py
