#!/bin/bash
#SBATCH -A mp309
#SBATCH -N 32
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J fenicsx
#SBATCH --ntasks-per-node=32
#SBATCH -t 00:30:00

#OpenMP settings:
#export OMP_NUM_THREADS=1
#export OMP_PLACES=threads
#export OMP_PROC_BIND=spread

#run the application:
srun -n 1024 python fix-fenicsx.py > bm-010-5120-5120-32-32-fenicsx.out
